import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";
import {
  AUDIT_MAINTENANCE_TASK_PREFIX,
  AuditMaintenanceProviderPolicyError,
  EngineeringAiAuditMaintainer,
  type TaskLifecycleEvent,
} from "../src/execution/audit-maintenance.js";
import {
  ENGINEERING_AI_AUDIT_STATUS_LEDGER_RELATIVE_PATH,
  ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH,
  ENGINEERING_AI_AUDIT_STATUS_FILENAME,
  ENGINEERING_AI_AUDIT_TIMELINE_FILENAME,
  type AuditMirrorEvidence,
} from "../src/execution/audit-mirror.js";
import type { ExecutionBackend, BackendExecutionRequest, BackendExecutionResult } from "../src/execution/backend.js";
import type { PersistedTaskRecord } from "../src/execution/tasks.js";
import { Workspace } from "../src/workspace/manager.js";
import { cleanup, isolateStateDir, makeTmpDir } from "./helpers.js";
import { writeWorkspaceQueuePauseState } from "../src/execution/queue-state.js";

describe("EngineeringAiAuditMaintainer", () => {
  const originalEnv = { ...process.env };
  const temporaryDirectories: string[] = [];

  beforeEach(() => {
    isolateStateDir();
  });

  afterEach(() => {
    for (const key of Object.keys(process.env)) {
      if (!(key in originalEnv)) {
        delete process.env[key];
      } else {
        process.env[key] = originalEnv[key];
      }
    }
    for (const dir of temporaryDirectories.splice(0)) {
      cleanup(dir);
    }
  });

  function createTestWorkspace(name: string): Workspace {
    const dir = makeTmpDir(name);
    temporaryDirectories.push(dir);
    fs.mkdirSync(path.join(dir, "docs"), { recursive: true });
    return new Workspace(dir);
  }

  function createMockGeminiBackend(
    executeFn?: (req: BackendExecutionRequest) => Promise<BackendExecutionResult>
  ): ExecutionBackend {
    return {
      provider: "gemini",
      execute:
        executeFn ??
        vi.fn().mockResolvedValue({
          status: "completed",
          output:
            "# CURRENT - C2C Audit Maintenance (2026-09-07T10:00:00.000Z)\n\nAudit summary text generated by Gemini.",
        }),
    };
  }

  it("honors maintenance pause before startup, execution, and shutdown flush", async () => {
    const workspace = createTestWorkspace("ws-paused-audit");
    const execute = vi.fn().mockResolvedValue({ status: "completed", output: "# CURRENT - Test" });
    writeWorkspaceQueuePauseState(workspace.id, true);
    const maintainer = new EngineeringAiAuditMaintainer({
      engineeringAiWorkspace: workspace,
      geminiBackend: createMockGeminiBackend(execute),
      fullAccess: true,
      debounceMs: 0,
    });
    expect(maintainer.isEnabled).toBe(false);
    maintainer.notifyEvent({ type: "restart", workspaceId: workspace.id, timestamp: new Date().toISOString() });
    await maintainer.catchUp();
    await maintainer.triggerRefresh();
    await maintainer.close();
    expect(execute).not.toHaveBeenCalled();
  });

  describe("Provider Policy Enforcement", () => {
    it("rejects non-gemini execution backends upfront", () => {
      const workspace = createTestWorkspace("ws-provider-reject");
      const codexBackend: ExecutionBackend = {
        provider: "codex" as any,
        execute: vi.fn(),
      };

      expect(() => {
        new EngineeringAiAuditMaintainer({
          engineeringAiWorkspace: workspace,
          geminiBackend: codexBackend,
        });
      }).toThrow(AuditMaintenanceProviderPolicyError);
    });

    it("rejects glm and unknown providers upfront", () => {
      const workspace = createTestWorkspace("ws-provider-reject-2");

      expect(() => {
        new EngineeringAiAuditMaintainer({
          engineeringAiWorkspace: workspace,
          geminiBackend: { provider: "glm" as any, execute: vi.fn() },
        });
      }).toThrow(AuditMaintenanceProviderPolicyError);

      expect(() => {
        new EngineeringAiAuditMaintainer({
          engineeringAiWorkspace: workspace,
          geminiBackend: { provider: "unknown" as any, execute: vi.fn() },
        });
      }).toThrow(AuditMaintenanceProviderPolicyError);
    });

    it("accepts gemini provider backend when fullAccess is authorized", () => {
      const workspace = createTestWorkspace("ws-provider-accept");
      const geminiBackend = createMockGeminiBackend();

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        fullAccess: true,
      });
      expect(maintainer.isEnabled).toBe(true);
      expect(maintainer.isAuthorized).toBe(true);
    });
  });

  describe("Execution Authorization Enforcement (fullAccess)", () => {
    it("fails closed by default when fullAccess is omitted; maintainer is disabled and execute() is never called", async () => {
      const workspace = createTestWorkspace("ws-unauth-default");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Should never run",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        debounceMs: 0,
      });

      expect(maintainer.isAuthorized).toBe(false);
      expect(maintainer.isEnabled).toBe(false);

      // Event notification should be ignored fail-closed
      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_unauth",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();

      // Catch-up should also be ignored fail-closed
      await maintainer.catchUp();
      await maintainer.close();

      expect(executeMock).not.toHaveBeenCalled();
    });

    it("fails closed when fullAccess is explicitly false; maintainer is disabled and execute() is never called", async () => {
      const workspace = createTestWorkspace("ws-unauth-false");
      const executeMock = vi.fn();
      const geminiBackend = createMockGeminiBackend(executeMock);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        fullAccess: false,
        debounceMs: 0,
      });

      expect(maintainer.isAuthorized).toBe(false);
      expect(maintainer.isEnabled).toBe(false);

      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: "c2c_task_unauth_false",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();
      await maintainer.close();

      expect(executeMock).not.toHaveBeenCalled();
    });

    it("regression: workspace + Gemini backend + fullAccess omitted/false => isEnabled false, notifyEvent/trigger/close never calls backend", async () => {
      for (const fullAccessValue of [undefined, false]) {
        const workspace = createTestWorkspace(`ws-unauth-regression-${String(fullAccessValue)}`);
        const executeMock = vi.fn().mockResolvedValue({
          status: "completed",
          output: "# CURRENT - Should never run",
        });
        const geminiBackend = createMockGeminiBackend(executeMock);

        const maintainer = new EngineeringAiAuditMaintainer({
          engineeringAiWorkspace: workspace,
          geminiBackend,
          ...(fullAccessValue !== undefined ? { fullAccess: fullAccessValue } : {}),
          debounceMs: 0,
        });

        expect(maintainer.isEnabled).toBe(false);
        expect(maintainer.isAuthorized).toBe(false);

        maintainer.notifyEvent({
          type: "start",
          workspaceId: workspace.id,
          taskId: "c2c_task_unauth_regression",
          timestamp: "2026-09-07T10:00:00.000Z",
        });

        await maintainer.triggerRefresh();
        await maintainer.close();

        expect(executeMock).not.toHaveBeenCalled();
      }
    });

    it("enables maintainer and permits execute() when fullAccess is explicitly true", async () => {
      const workspace = createTestWorkspace("ws-auth-true");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Authorized run",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      expect(maintainer.isAuthorized).toBe(true);
      expect(maintainer.isEnabled).toBe(true);

      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_auth",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();

      expect(executeMock).toHaveBeenCalledTimes(1);
      const request = executeMock.mock.calls[0][0] as BackendExecutionRequest;
      expect(request.networkRequested).toBe(true);
      expect(request.networkEffective).toBe(true);
      expect(request.fullAccess).toBe(true);

      await maintainer.close();
    });
  });

  describe("Workspace Resolution & Fail-Closed Behavior", () => {
    it("fails closed / disabled when no Engineering AI workspace is resolvable", () => {
      delete process.env.C2C_ENGINEERING_AI_WORKSPACE_ID;
      delete process.env.C2C_ENGINEERING_AI_WORKSPACE_ROOT;

      const geminiBackend = createMockGeminiBackend();
      const maintainer = new EngineeringAiAuditMaintainer({
        geminiBackend,
        fullAccess: true,
      });

      expect(maintainer.isEnabled).toBe(false);
    });

    it("resolves workspace via C2C_ENGINEERING_AI_WORKSPACE_ROOT env var", () => {
      const workspaceDir = makeTmpDir("ws-env-root");
      temporaryDirectories.push(workspaceDir);
      process.env.C2C_ENGINEERING_AI_WORKSPACE_ROOT = workspaceDir;

      const geminiBackend = createMockGeminiBackend();
      const maintainer = new EngineeringAiAuditMaintainer({
        geminiBackend,
        fullAccess: true,
      });

      expect(maintainer.isEnabled).toBe(true);
    });

    it("respects explicit disabled flag even if workspace is supplied", () => {
      const workspace = createTestWorkspace("ws-disabled");
      const geminiBackend = createMockGeminiBackend();

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        disabled: true,
        fullAccess: true,
      });

      expect(maintainer.isEnabled).toBe(false);
    });
  });

  describe("Recursion Prevention", () => {
    it("ignores events flagged with isAuditMaintenance = true", async () => {
      const workspace = createTestWorkspace("ws-rec-1");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Test",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: "task_123",
        timestamp: "2026-09-07T10:00:00.000Z",
        isAuditMaintenance: true,
      });

      await maintainer.triggerRefresh();
      expect(executeMock).not.toHaveBeenCalled();
    });

    it("ignores events whose taskId starts with audit maintenance task prefix", async () => {
      const workspace = createTestWorkspace("ws-rec-2");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Test",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: `${AUDIT_MAINTENANCE_TASK_PREFIX}999999`,
        timestamp: "2026-09-07T10:00:00.000Z",
      });

      await maintainer.triggerRefresh();
      expect(executeMock).not.toHaveBeenCalled();
    });
  });

  describe("Burst Coalescing & Concurrency Coordination", () => {
    it("coalesces rapid burst of events into a single Gemini execution", async () => {
      const workspace = createTestWorkspace("ws-coalesce");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Coalesced\n\nAll events handled.",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({
        success: true,
        code: "OK",
        logicalTarget: "mock",
        resolvedTarget: null,
        timestampUtc: new Date().toISOString(),
        byteCount: 100,
        sha256: "abc",
        source: "engineering_ai_ledger",
        targetFilename: ENGINEERING_AI_AUDIT_STATUS_FILENAME,
        targetSha256: "abc",
      } as AuditMirrorEvidence);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 50,
      });

      for (let i = 1; i <= 5; i++) {
        maintainer.notifyEvent({
          type: "start",
          workspaceId: workspace.id,
          taskId: `c2c_task_${i}`,
          timestamp: `2026-09-07T10:00:0${i}.000Z`,
        });
      }

      // Wait for debounce timer
      await new Promise((resolve) => setTimeout(resolve, 100));

      expect(executeMock).toHaveBeenCalledTimes(1);
      const instruction = executeMock.mock.calls[0][0].instruction as string;
      expect(instruction).toContain("c2c_task_1");
      expect(instruction).toContain("c2c_task_5");

      await maintainer.close();
    });

    it("serializes concurrent refreshes without overlapping backend executions", async () => {
      const workspace = createTestWorkspace("ws-single-writer");
      let inFlight = false;
      let overlapDetected = false;

      const executeMock = vi.fn().mockImplementation(async () => {
        if (inFlight) overlapDetected = true;
        inFlight = true;
        await new Promise((resolve) => setTimeout(resolve, 50));
        inFlight = false;
        return {
          status: "completed",
          output: "# CURRENT - Single Writer Done",
        };
      });

      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({
        success: true,
        code: "OK",
      } as unknown as AuditMirrorEvidence);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      // Fire first event
      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_1",
        timestamp: "2026-09-07T10:00:01.000Z",
      });

      // Wait 10ms so first execution is actively in-flight
      await new Promise((resolve) => setTimeout(resolve, 10));

      // Fire second event while first is in-flight
      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: "c2c_task_1",
        timestamp: "2026-09-07T10:00:02.000Z",
      });

      // Wait for both rounds to complete
      await new Promise((resolve) => setTimeout(resolve, 200));

      expect(overlapDetected).toBe(false);
      expect(executeMock).toHaveBeenCalledTimes(2);

      await maintainer.close();
    });
  });

  describe("Real-time Timeline & Append-Only Behavior", () => {
    it("records both start and completed events for the same task without suppression", async () => {
      const workspace = createTestWorkspace("ws-timeline-events");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Updated",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      const taskRecord: PersistedTaskRecord = {
        taskId: "c2c_0123456789abcdef",
        workspaceId: workspace.id,
        instruction: "run audit",
        status: "running",
        submittedAt: "2026-09-07T10:00:00.000Z",
        startedAt: "2026-09-07T10:00:01.000Z",
        provider: "gemini",
        providerModel: "gemini-2.5-pro",
        networkRequested: true,
        networkEffective: true,
        networkReported: true,
      };

      // 1. Emit start event
      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: taskRecord.taskId,
        record: taskRecord,
        timestamp: "2026-09-07T10:00:01.000Z",
      });

      await new Promise((resolve) => setTimeout(resolve, 50));

      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      expect(fs.existsSync(timelinePath)).toBe(true);
      let content = fs.readFileSync(timelinePath, "utf8");
      expect(content).toContain("Event [start] - c2c_0123456789abcdef");
      expect(content).toContain("gemini / gemini-2.5-pro");
      expect(content).toContain("req=true, eff=true, rep=true");

      // 2. Emit completed event for the same task
      const completedRecord: PersistedTaskRecord = {
        ...taskRecord,
        status: "completed",
        completedAt: "2026-09-07T10:00:10.000Z",
        exitStatus: "ok",
        changedFiles: ["src/index.ts", "package.json"],
        tests: "pass",
        restartRequired: false,
      };

      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: completedRecord.taskId,
        record: completedRecord,
        timestamp: "2026-09-07T10:00:10.000Z",
      });

      await new Promise((resolve) => setTimeout(resolve, 50));

      content = fs.readFileSync(timelinePath, "utf8");
      expect(content).toContain("Event [start] - c2c_0123456789abcdef");
      expect(content).toContain("Event [completed] - c2c_0123456789abcdef");
      expect(content).toContain("src/index.ts, package.json");
      expect(content).toContain("completed (ok)");
      expect(content).toContain("| tests | pass |");
      expect(content).toContain("| restart_required | false |");

      await maintainer.close();
    });

    it("records 'not supplied' truthfully without inventing missing values", async () => {
      const workspace = createTestWorkspace("ws-timeline-missing");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Minimal",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "queue_paused",
        workspaceId: workspace.id,
        paused: true,
        timestamp: "2026-09-07T10:00:00.000Z",
      });

      await new Promise((resolve) => setTimeout(resolve, 50));

      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      const content = fs.readFileSync(timelinePath, "utf8");
      expect(content).toContain("Event [queue_paused]");
      expect(content).toContain("| task_id | not supplied |");
      expect(content).toContain("| provider_model | not supplied |");
      expect(content).toContain("| network | req=not supplied, eff=not supplied, rep=not supplied |");
      expect(content).toContain("| changed_files | none |");
      expect(content).toContain("| queue_paused | true |");

      await maintainer.close();
    });

    it("deduplicates identical events to avoid duplicate timeline sections", async () => {
      const workspace = createTestWorkspace("ws-dedup");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Dedup",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      const event: TaskLifecycleEvent = {
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_duplicate_test",
        timestamp: "2026-09-07T10:00:00.000Z",
      };

      maintainer.notifyEvent(event);
      await maintainer.triggerRefresh();

      // Send same event again
      maintainer.notifyEvent(event);
      await maintainer.triggerRefresh();

      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      const content = fs.readFileSync(timelinePath, "utf8");
      const matches = content.split("Event [start] - c2c_duplicate_test").length - 1;
      expect(matches).toBe(1);

      await maintainer.close();
    });
  });

  describe("Status File - Authoritative CURRENT & Retained History", () => {
    it("replaces the single top authoritative CURRENT section and leaves retained history byte-for-byte unchanged", async () => {
      const workspace = createTestWorkspace("ws-status-history");
      const statusPath = path.join(workspace.root, ENGINEERING_AI_AUDIT_STATUS_LEDGER_RELATIVE_PATH);
      fs.mkdirSync(path.dirname(statusPath), { recursive: true });

      const marker = "## Retained historical snapshots and prior CURRENT sections";
      const legacyHistory = "\n\n### Legacy Baseline Snapshot\nPermanent legacy content preserved forever.\n";
      const initialStatus = `# CURRENT - Initial Manual State\n\nManual status body.\n\n${marker}${legacyHistory}`;
      fs.writeFileSync(statusPath, initialStatus, "utf8");

      const markerIdx = initialStatus.indexOf(marker);
      const expectedRetainedBlock = initialStatus.slice(markerIdx);

      let callCount = 0;
      const executeMock = vi.fn().mockImplementation(async () => {
        callCount++;
        return {
          status: "completed",
          output: `# CURRENT - C2C Audit Maintenance (Iteration ${callCount})\n\nAuthoritative summary for iteration ${callCount}.`,
        };
      });

      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      // Iteration 1
      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_a",
        timestamp: "2026-09-07T10:00:01.000Z",
      });
      await maintainer.triggerRefresh();

      let content = fs.readFileSync(statusPath, "utf8");
      expect(content.startsWith("# CURRENT - C2C Audit Maintenance (Iteration 1)")).toBe(true);
      expect(content).toContain("Authoritative summary for iteration 1.");
      // Prior CURRENT was replaced, NOT demoted into retained history
      expect(content).not.toContain("Prior Snapshot");
      expect(content).not.toContain("Manual status body.");
      // Retained block remains byte-for-byte unchanged
      const currentMarkerIdx1 = content.indexOf(marker);
      expect(currentMarkerIdx1).toBeGreaterThan(0);
      expect(content.slice(currentMarkerIdx1)).toBe(expectedRetainedBlock);

      // Iteration 2
      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: "c2c_task_a",
        timestamp: "2026-09-07T10:00:02.000Z",
      });
      await maintainer.triggerRefresh();

      content = fs.readFileSync(statusPath, "utf8");
      // Must start with the new CURRENT section
      expect(content.startsWith("# CURRENT - C2C Audit Maintenance (Iteration 2)")).toBe(true);
      expect(content).toContain("Authoritative summary for iteration 2.");
      // Previous iteration was replaced, NOT demoted into retained history
      expect(content).not.toContain("Authoritative summary for iteration 1.");
      expect(content).not.toContain("Prior Snapshot");
      // Retained block remains byte-for-byte unchanged
      const currentMarkerIdx2 = content.indexOf(marker);
      expect(currentMarkerIdx2).toBeGreaterThan(0);
      expect(content.slice(currentMarkerIdx2)).toBe(expectedRetainedBlock);

      // Verify exactly one top # CURRENT heading in entire file
      const currentMatches = content.match(/^# CURRENT/gm) || [];
      expect(currentMatches.length).toBe(1);

      await maintainer.close();
    });

    it("regression: seeds a retained-history block, performs at least 10 refreshes, asserts exactly one top-level # CURRENT, retained block byte-for-byte unchanged, and no Prior Snapshot accumulation", async () => {
      const workspace = createTestWorkspace("ws-status-no-demotion-regression");
      const statusPath = path.join(workspace.root, ENGINEERING_AI_AUDIT_STATUS_LEDGER_RELATIVE_PATH);
      fs.mkdirSync(path.dirname(statusPath), { recursive: true });

      const marker = "## Retained historical snapshots and prior CURRENT sections";
      const legacyBlock = `${marker}\n\n### Preserved Historical Log\n- 2026-09-01: Baseline established\n- 2026-09-02: Legacy verification passed\n`;
      const initialContent = `# CURRENT - Baseline\n\nBaseline summary.\n\n${legacyBlock}`;
      fs.writeFileSync(statusPath, initialContent, "utf8");

      const expectedRetainedBlock = legacyBlock;
      let iteration = 0;

      const executeMock = vi.fn().mockImplementation(async () => {
        iteration++;
        return {
          status: "completed",
          output: `# CURRENT - C2C Audit Maintenance (Round ${iteration})\n\nDetailed status for round ${iteration}.`,
        };
      });

      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      const totalRefreshes = 15;
      const recordedLengths: number[] = [];

      for (let i = 1; i <= totalRefreshes; i++) {
        maintainer.notifyEvent({
          type: i % 2 === 1 ? "start" : "completed",
          workspaceId: workspace.id,
          taskId: `c2c_task_burst_${i}`,
          timestamp: `2026-09-07T10:00:${i < 10 ? `0${i}` : i}.000Z`,
        });
        await maintainer.triggerRefresh();

        const currentContent = fs.readFileSync(statusPath, "utf8");
        recordedLengths.push(currentContent.length);

        // Exactly one top-level # CURRENT heading
        const currentMatches = currentContent.match(/^# CURRENT/gm) || [];
        expect(currentMatches.length).toBe(1);

        // Must start with current round heading
        expect(currentContent.startsWith(`# CURRENT - C2C Audit Maintenance (Round ${i})`)).toBe(true);

        // Retained history block must be byte-for-byte unchanged
        const markerIndex = currentContent.indexOf(marker);
        expect(markerIndex).toBeGreaterThan(0);
        expect(currentContent.slice(markerIndex)).toBe(expectedRetainedBlock);

        // No Prior Snapshot accumulation
        expect(currentContent).not.toContain("Prior Snapshot");
      }

      expect(executeMock).toHaveBeenCalledTimes(totalRefreshes);

      // Verify no linear history growth: lengths differ only by single-character iteration index changes
      const firstLength = recordedLengths[0];
      const lastLength = recordedLengths[recordedLengths.length - 1];
      expect(Math.abs(lastLength - firstLength)).toBeLessThanOrEqual(5);

      await maintainer.close();
    });
  });

  describe("Canonical Precedes Mirror & Mirror Failure Handling", () => {
    it("writes canonical status and timeline to disk BEFORE calling mirrorWriter", async () => {
      const workspace = createTestWorkspace("ws-canonical-first");
      const geminiBackend = createMockGeminiBackend();

      const statusPath = path.join(workspace.root, ENGINEERING_AI_AUDIT_STATUS_LEDGER_RELATIVE_PATH);
      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);

      let canonicalStatusExistedDuringMirror = false;
      let canonicalTimelineExistedDuringMirror = false;

      const mirrorWriter = vi.fn().mockImplementation(async (opts) => {
        if (fs.existsSync(statusPath)) canonicalStatusExistedDuringMirror = true;
        if (fs.existsSync(timelinePath)) canonicalTimelineExistedDuringMirror = true;
        return {
          success: true,
          code: "OK",
          logicalTarget: opts.requestedPath,
          resolvedTarget: null,
          timestampUtc: new Date().toISOString(),
          byteCount: 50,
          sha256: "hash",
          source: "engineering_ai_ledger",
          targetFilename: ENGINEERING_AI_AUDIT_STATUS_FILENAME,
          targetSha256: "hash",
        } as AuditMirrorEvidence;
      });

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_order",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();

      expect(canonicalStatusExistedDuringMirror).toBe(true);
      expect(canonicalTimelineExistedDuringMirror).toBe(true);
      expect(maintainer.isDegraded).toBe(false);

      await maintainer.close();
    });

    it("leaves canonical files intact and persists DEGRADED state when mirrorWriter fails", async () => {
      const workspace = createTestWorkspace("ws-mirror-fail");
      const geminiBackend = createMockGeminiBackend();

      const statusPath = path.join(workspace.root, ENGINEERING_AI_AUDIT_STATUS_LEDGER_RELATIVE_PATH);
      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);

      // Mirror writer throws an error
      const mirrorWriter = vi.fn().mockRejectedValue(new Error("OneDrive network unreachable"));

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: "c2c_task_mirror_err",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();

      // Canonical files MUST exist and be intact
      expect(fs.existsSync(statusPath)).toBe(true);
      expect(fs.existsSync(timelinePath)).toBe(true);
      expect(fs.readFileSync(statusPath, "utf8")).toContain("# CURRENT");
      expect(fs.readFileSync(timelinePath, "utf8")).toContain("c2c_task_mirror_err");

      // Maintainer must be in DEGRADED state with pending mirror retry
      expect(maintainer.isDegraded).toBe(true);
      expect(maintainer.hasPendingMirror).toBe(true);

      const persistedState = maintainer.readPersistedState();
      expect(persistedState?.status).toBe("DEGRADED");
      expect(persistedState?.error?.code).toBe("MIRROR_WRITE_FAILED");
      expect(persistedState?.pendingMirrorRetry).toBe(true);

      await maintainer.close();
    });
  });

  describe("Startup Catch-up & Mirror Retry", () => {
    it("retries pending mirror writes during catchUp() and transitions to HEALTHY on success", async () => {
      const workspace = createTestWorkspace("ws-catchup-mirror");
      const geminiBackend = createMockGeminiBackend();

      let mirrorShouldSucceed = false;
      const mirrorWriter = vi.fn().mockImplementation(async (opts) => {
        if (!mirrorShouldSucceed) {
          return { success: false, code: "MIRROR_WRITE_FAILED" } as AuditMirrorEvidence;
        }
        return { success: true, code: "OK" } as AuditMirrorEvidence;
      });

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 0,
      });

      maintainer.notifyEvent({
        type: "start",
        workspaceId: workspace.id,
        taskId: "c2c_task_retry",
        timestamp: "2026-09-07T10:00:00.000Z",
      });
      await maintainer.triggerRefresh();

      expect(maintainer.isDegraded).toBe(true);
      expect(maintainer.hasPendingMirror).toBe(true);

      // Now mirror recovers
      mirrorShouldSucceed = true;
      await maintainer.catchUp();

      expect(maintainer.isDegraded).toBe(false);
      expect(maintainer.hasPendingMirror).toBe(false);
      const state = maintainer.readPersistedState();
      expect(state?.status).toBe("HEALTHY");
      expect(state?.pendingMirrorRetry).toBe(false);

      await maintainer.close();
    });

    it("scans persisted task directory on startup to reconcile missed terminal tasks", async () => {
      const workspace = createTestWorkspace("ws-catchup-tasks");
      const stateDir = isolateStateDir();
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Reconciled",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      // Write an un-reconciled terminal task directly to state tasks directory
      const tasksDir = path.join(stateDir, "tasks", workspace.id);
      fs.mkdirSync(tasksDir, { recursive: true });
      const taskRecord: PersistedTaskRecord = {
        taskId: "c2c_missed_01",
        workspaceId: workspace.id,
        instruction: "missed offline task",
        status: "completed",
        submittedAt: "2026-09-07T09:00:00.000Z",
        startedAt: "2026-09-07T09:00:01.000Z",
        completedAt: "2026-09-07T09:00:05.000Z",
        exitStatus: "ok",
        provider: "gemini",
        providerModel: "gemini-2.5-flash",
      };
      fs.writeFileSync(path.join(tasksDir, "c2c_missed_01.json"), JSON.stringify(taskRecord, null, 2), "utf8");

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        stateDir,
        fullAccess: true,
        debounceMs: 0,
      });

      await maintainer.catchUp();

      expect(executeMock).toHaveBeenCalledTimes(1);
      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      const content = fs.readFileSync(timelinePath, "utf8");
      expect(content).toContain("c2c_missed_01");
      expect(content).toContain("Event [completed]");

      await maintainer.close();
    });

    it("reconciles missed completed terminal event when timeline already contains a start event, and repeated catchUp does not duplicate", async () => {
      const workspace = createTestWorkspace("ws-catchup-start-to-completed");
      const stateDir = isolateStateDir();
      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      const taskId = "c2c_regression_task_01";
      const startTime = "2026-09-07T10:00:00.000Z";
      const completedTime = "2026-09-07T10:00:15.000Z";

      // 1. Pre-populate timeline with only a START event
      const startKey = `${taskId}:start:${startTime}`;
      const startKeyTag = `<!-- event-key:${startKey} -->`;
      const initialTimeline = [
        "# Audit execution timeline",
        "",
        "This append-only file is the canonical timeline for C2C execution metadata.",
        "",
        `## Event [start] - ${taskId} (${startTime}) ${startKeyTag}`,
        "",
        "| field | value |",
        "|---|---|",
        "| event_type | `start` |",
        `| workspace_id | \`${workspace.id}\` |`,
        `| task_id | \`${taskId}\` |`,
        "| provider_model | gemini / gemini-2.5-pro |",
        `| started_at_utc | ${startTime} |`,
        "| completed_at_utc | not supplied |",
        "| network | req=true, eff=true, rep=true |",
        "| status_outcome | running |",
        "| changed_files | none |",
        "| tests | not supplied |",
        "| restart_required | not supplied |",
        "| queue_paused | not supplied |",
        "",
      ].join("\n");
      fs.mkdirSync(path.dirname(timelinePath), { recursive: true });
      fs.writeFileSync(timelinePath, initialTimeline, "utf8");

      // 2. Persist the same task as COMPLETED in state tasks directory
      const tasksDir = path.join(stateDir, "tasks", workspace.id);
      fs.mkdirSync(tasksDir, { recursive: true });
      const completedRecord: PersistedTaskRecord = {
        taskId,
        workspaceId: workspace.id,
        instruction: "run regression verification",
        status: "completed",
        submittedAt: "2026-09-07T09:59:50.000Z",
        startedAt: startTime,
        completedAt: completedTime,
        exitStatus: "ok",
        provider: "gemini",
        providerModel: "gemini-2.5-pro",
        changedFiles: ["src/feature.ts"],
        tests: "pass",
        restartRequired: false,
      };
      fs.writeFileSync(path.join(tasksDir, `${taskId}.json`), JSON.stringify(completedRecord, null, 2), "utf8");

      // 3. Create maintainer and trigger catchUp()
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Reconciled Completed Task",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        stateDir,
        fullAccess: true,
        debounceMs: 0,
      });

      await maintainer.catchUp();

      // 4. Assert completed event is appended exactly once and start remains
      expect(executeMock).toHaveBeenCalledTimes(1);
      let timelineContent = fs.readFileSync(timelinePath, "utf8");
      expect(timelineContent).toContain(`Event [start] - ${taskId}`);
      expect(timelineContent).toContain(`Event [completed] - ${taskId}`);
      expect(timelineContent).toContain("src/feature.ts");
      expect(timelineContent).toContain("completed (ok)");

      const startCount = timelineContent.split(`Event [start] - ${taskId}`).length - 1;
      const completedCount = timelineContent.split(`Event [completed] - ${taskId}`).length - 1;
      expect(startCount).toBe(1);
      expect(completedCount).toBe(1);

      // 5. Ensure repeated catchUp() does NOT duplicate the terminal event
      await maintainer.catchUp();

      expect(executeMock).toHaveBeenCalledTimes(1); // not called again
      timelineContent = fs.readFileSync(timelinePath, "utf8");
      const completedCountAfterSecond = timelineContent.split(`Event [completed] - ${taskId}`).length - 1;
      expect(completedCountAfterSecond).toBe(1);

      await maintainer.close();
    });

    it("preserves legacy compatibility: suppresses catch-up when legacy timeline mentions taskId without event keys", async () => {
      const workspace = createTestWorkspace("ws-catchup-legacy");
      const stateDir = isolateStateDir();
      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      const legacyTaskId = "c2c_legacy_task_99";

      // 1. Timeline mentions taskId in a legacy format without <!-- event-key:... -->
      const legacyTimeline = `# Audit execution timeline\n\nLegacy execution for ${legacyTaskId} completed.\n`;
      fs.mkdirSync(path.dirname(timelinePath), { recursive: true });
      fs.writeFileSync(timelinePath, legacyTimeline, "utf8");

      // 2. Persist the task in state tasks dir
      const tasksDir = path.join(stateDir, "tasks", workspace.id);
      fs.mkdirSync(tasksDir, { recursive: true });
      const record: PersistedTaskRecord = {
        taskId: legacyTaskId,
        workspaceId: workspace.id,
        instruction: "legacy task",
        status: "completed",
        submittedAt: "2026-09-07T08:00:00.000Z",
        completedAt: "2026-09-07T08:01:00.000Z",
        exitStatus: "ok",
      };
      fs.writeFileSync(path.join(tasksDir, `${legacyTaskId}.json`), JSON.stringify(record, null, 2), "utf8");

      const executeMock = vi.fn();
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        stateDir,
        fullAccess: true,
        debounceMs: 0,
      });

      await maintainer.catchUp();

      // Legacy mention should suppress catch-up
      expect(executeMock).not.toHaveBeenCalled();
      const finalTimeline = fs.readFileSync(timelinePath, "utf8");
      expect(finalTimeline).toBe(legacyTimeline);

      await maintainer.close();
    });
  });

  describe("Close & Debounce Flush Acceptance", () => {
    it("regression: queues a debounced event, calls close immediately, asserts Gemini executes once and canonical timeline contains the event before close resolves", async () => {
      const workspace = createTestWorkspace("ws-close-flush-regression");
      const executeMock = vi.fn().mockResolvedValue({
        status: "completed",
        output: "# CURRENT - Flushed On Close\n\nDebounced event flushed successfully.",
      });
      const geminiBackend = createMockGeminiBackend(executeMock);
      const mirrorWriter = vi.fn().mockResolvedValue({ success: true, code: "OK" } as any);

      // Set a long debounce (5000ms) so an ordinary timer would not fire immediately
      const maintainer = new EngineeringAiAuditMaintainer({
        engineeringAiWorkspace: workspace,
        geminiBackend,
        mirrorWriter,
        fullAccess: true,
        debounceMs: 5000,
      });

      const flushedTaskId = "c2c_task_debounced_close_flush";
      maintainer.notifyEvent({
        type: "completed",
        workspaceId: workspace.id,
        taskId: flushedTaskId,
        timestamp: "2026-09-07T10:00:00.000Z",
      });

      // Assert that execute has not been called yet (due to debounce)
      expect(executeMock).not.toHaveBeenCalled();

      let executeCountBeforeCloseResolves = 0;
      let timelineHadEventBeforeCloseResolves = false;

      // Call close immediately and inspect state right as close resolves
      await maintainer.close().then(() => {
        executeCountBeforeCloseResolves = executeMock.mock.calls.length;
        const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
        if (fs.existsSync(timelinePath)) {
          const content = fs.readFileSync(timelinePath, "utf8");
          if (content.includes(flushedTaskId)) {
            timelineHadEventBeforeCloseResolves = true;
          }
        }
      });

      // Assert Gemini executed once and canonical timeline contains the event before close resolves
      expect(executeCountBeforeCloseResolves).toBe(1);
      expect(timelineHadEventBeforeCloseResolves).toBe(true);
      expect(executeMock).toHaveBeenCalledTimes(1);

      const timelinePath = path.join(workspace.root, ENGINEERING_AI_AUDIT_TIMELINE_LEDGER_RELATIVE_PATH);
      expect(fs.existsSync(timelinePath)).toBe(true);
      const content = fs.readFileSync(timelinePath, "utf8");
      expect(content).toContain(flushedTaskId);
      expect(content).toContain(`Event [completed] - ${flushedTaskId}`);
    });
  });
});
